"""Compare candidate intent classifiers on the VITmate dataset.

Trains a classical TF-IDF + logistic-regression baseline and several pretrained
transformers of different sizes. Selection uses *validation* macro-F1 only;
test and spoken-test scores are reported for completeness. Results are written
to docs/results/model_comparison.{json,md}.

Runs accumulate in the JSON file (one entry per candidate and seed), so extra
seeds can be added later and the table reports the mean and standard deviation.

Usage:
    python -m training.compare_models                                   # all candidates, seed 42
    python -m training.compare_models --only minilm-l6 bge-small --seeds 7 13
"""

from __future__ import annotations

import argparse
import json
import logging
import statistics
import time
from dataclasses import replace
from pathlib import Path

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import FeatureUnion, make_pipeline

from backend.app.ml.intent_classifier import IntentClassifier
from training.common import classification_metrics, load_split, write_json
from training.paths import ARTIFACTS_DIR, RESULTS_DIR
from training.train import TrainConfig, fine_tune

logger = logging.getLogger("compare")

CANDIDATES = {
    "bert-mini": TrainConfig("google/bert_uncased_L-4_H-256_A-4", learning_rate=2e-4),
    "minilm-l6": TrainConfig("sentence-transformers/all-MiniLM-L6-v2", learning_rate=1e-4),
    "bge-small": TrainConfig("BAAI/bge-small-en-v1.5", learning_rate=1e-4),
    "distilbert": TrainConfig("distilbert-base-uncased", learning_rate=5e-5),
}
EVAL_SPLITS = ("val", "test", "spoken_test")


def median_latency_ms(predict_one, texts: list[str], repeats: int = 3) -> float:
    """Median single-query latency, the way the API serves requests."""
    timings = []
    for _ in range(repeats):
        for text in texts:
            started = time.perf_counter()
            predict_one(text)
            timings.append((time.perf_counter() - started) * 1000)
    return round(statistics.median(timings), 2)


def directory_size_mb(path: Path) -> float:
    return round(sum(f.stat().st_size for f in path.rglob("*") if f.is_file()) / 1e6, 1)


def evaluate_predictor(predict_many, predict_one) -> dict:
    result = {}
    for split in EVAL_SPLITS:
        texts, gold = load_split(split)
        result[split] = classification_metrics(gold, predict_many(texts))
    val_texts, _ = load_split("val")
    result["median_latency_ms"] = median_latency_ms(predict_one, val_texts[:100])
    return result


def run_baseline() -> dict:
    texts, intents = load_split("train")
    features = FeatureUnion([
        ("word", TfidfVectorizer(ngram_range=(1, 2), sublinear_tf=True)),
        ("char", TfidfVectorizer(analyzer="char_wb", ngram_range=(2, 5), sublinear_tf=True)),
    ])
    pipeline = make_pipeline(features, LogisticRegression(C=10, max_iter=3000, class_weight="balanced"))
    started = time.perf_counter()
    pipeline.fit(texts, intents)
    result = evaluate_predictor(lambda t: list(pipeline.predict(t)), lambda t: pipeline.predict([t]))
    result.update({"model_name": "TF-IDF (word+char) + Logistic Regression", "deep_learning": False,
                   "training_seconds": round(time.perf_counter() - started, 1)})
    return result


def run_transformer(key: str, config: TrainConfig) -> dict:
    output_dir = ARTIFACTS_DIR / "candidates" / f"{key}-seed{config.seed}"
    summary = fine_tune(config, output_dir)
    classifier = IntentClassifier(output_dir, max_length=config.max_length)
    result = evaluate_predictor(
        lambda texts: [p.intent for p in classifier.predict_batch(texts)], classifier.predict
    )
    result.update({
        "model_name": config.model_name,
        "deep_learning": True,
        "learning_rate": config.learning_rate,
        "seed": config.seed,
        "best_epoch": summary["best_epoch"],
        "training_seconds": summary["training_seconds"],
        "parameters_millions": round(summary["num_parameters"] / 1e6, 1),
        "size_mb": directory_size_mb(output_dir),
        "load_seconds": round(classifier.load_seconds, 2),
    })
    return result


def aggregate(runs: dict[str, dict]) -> dict[str, dict]:
    """Group runs stored as '<candidate>@seed<n>' by candidate."""
    grouped: dict[str, list[dict]] = {}
    for run_key, run in runs.items():
        grouped.setdefault(run_key.split("@")[0], []).append(run)
    return grouped


def mean_std(values: list[float]) -> str:
    if len(values) == 1:
        return f"{values[0]:.4f}"
    return f"{statistics.mean(values):.4f} ± {statistics.stdev(values):.4f}"


def write_markdown(runs: dict[str, dict], path: Path) -> None:
    lines = [
        "# Model comparison",
        "",
        "Generated by `python -m training.compare_models`. Selection criterion: validation macro-F1 "
        "(ties broken by latency). Test and spoken-test columns were **not** used for selection. "
        "Where several seeds were run, values are mean ± standard deviation.",
        "",
        "| Candidate | Seeds | Params (M) | Size fp32 (MB) | Val macro-F1 | Test accuracy | Test macro-F1 "
        "| Test weighted-F1 | Spoken accuracy | Spoken macro-F1 | Latency (ms) | Train (s) |",
        "|---|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for key, group in aggregate(runs).items():
        first = group[0]
        col = lambda split, metric: mean_std([r[split][metric] for r in group])  # noqa: E731
        lines.append(
            f"| {key} (`{first['model_name']}`) | {len(group)} | {first.get('parameters_millions', '-')} "
            f"| {first.get('size_mb', '-')} | {col('val', 'macro_f1')} | {col('test', 'accuracy')} "
            f"| {col('test', 'macro_f1')} | {col('test', 'weighted_f1')} | {col('spoken_test', 'accuracy')} "
            f"| {col('spoken_test', 'macro_f1')} | {statistics.median(r['median_latency_ms'] for r in group)} "
            f"| {statistics.mean(r['training_seconds'] for r in group):.0f} |"
        )
    path.write_text("\n".join(lines) + "\n")


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(name)s %(message)s", datefmt="%H:%M:%S")
    parser = argparse.ArgumentParser()
    parser.add_argument("--only", nargs="*", choices=["baseline", *CANDIDATES])
    parser.add_argument("--seeds", nargs="*", type=int, default=[42])
    args = parser.parse_args()
    selected = args.only or ["baseline", *CANDIDATES]

    results_file = RESULTS_DIR / "model_comparison.json"
    runs: dict[str, dict] = json.loads(results_file.read_text()) if results_file.exists() else {}
    for key in selected:
        for seed in [42] if key == "baseline" else args.seeds:  # the baseline is deterministic
            logger.info("=== %s (seed %d) ===", key, seed)
            runs[f"{key}@seed{seed}"] = (
                run_baseline() if key == "baseline" else run_transformer(key, replace(CANDIDATES[key], seed=seed))
            )
            write_json(results_file, runs)

    write_markdown(runs, RESULTS_DIR / "model_comparison.md")
    grouped = {k: g for k, g in aggregate(runs).items() if g[0]["deep_learning"]}
    best = max(grouped, key=lambda k: (statistics.mean(r["val"]["macro_f1"] for r in grouped[k]),
                                       -grouped[k][0]["median_latency_ms"]), default=None)
    logger.info("Best deep-learning candidate by mean validation macro-F1: %s", best)


if __name__ == "__main__":
    main()
